a = float(input("Digite qualquer valor para A: ")) 
b = float(input("Digite qualquer valor para B: ")) 
print(f"A + B = {(a):.1f} + {(b):.1f} = {(a+b):.1f}")
print(f"A - B = {(a):.1f} + {(b):.1f} = {(a-b):.1f}")
print(f"A X B = {(a):.1f} + {(b):.1f} = {(a*b):.1f}")
print(f"A / B = {(a):.1f} + {(b):.1f} = {(a/b):.1f}")
