a = int(input("Digite um número inteiro para A: "))
b = int(input("Digite um número inteiro para B: "))
c = int(input("Digite um número inteiro para C: "))
d = int(input("Digite um número inteiro para D: "))
print("Soma:")
print(f"A + B = {(a+b):.1f}")
print(f"A + C = {(a+c):.1f}")
print(f"A + D = {(a+d):.1f}")
print("Multiplicação:")
print(f"A X B = {(a*b):.1f}")
print(f"A X C = {(a*c):.1f}")
print(f"A X D = {(a*d):.1f}")